name: First Batch Workflow

on: 
  push:
    branches:
      - 'first-branch'
  pull_request:  
    branches:
      - 'first-branch'

jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Echo branch, checkout repo, and list files
        run: |
          echo ${GITHUB_REF##*/}
          echo "first-branch - first brach"
          
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List Files After Checkout
        run: |
          pwd
          ls -lah
          cat first-batch.txt
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_EVENT_NAME
          # echo ${{ secrets.GITHUB_TOKEN }}
