name: First Batch Workflow

on: 
  push:
    branches:
      - 'first-branch'
jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from first-branch
        run: echo "first-branch - first brach"
